// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AeroSim2026.EFModels;

public partial class Aerosim2026Context : DbContext
{
    public Aerosim2026Context(DbContextOptions<Aerosim2026Context> options)
        : base(options)
    {
    }

    public virtual DbSet<AircraftManufacturer> AircraftManufacturers { get; set; }

    public virtual DbSet<AircraftModel> AircraftModels { get; set; }

    public virtual DbSet<AircraftProperty> AircraftProperties { get; set; }

    public virtual DbSet<AircraftType> AircraftTypes { get; set; }

    public virtual DbSet<Airport> Airports { get; set; }

    public virtual DbSet<AirportType> AirportTypes { get; set; }

    public virtual DbSet<AirportsCom> AirportsComs { get; set; }

    public virtual DbSet<AirportsLocation> AirportsLocations { get; set; }

    public virtual DbSet<AirportsMsa> AirportsMsas { get; set; }

    public virtual DbSet<Airway> Airways { get; set; }

    public virtual DbSet<Approach> Approaches { get; set; }

    public virtual DbSet<ApproachLeg> ApproachLegs { get; set; }

    public virtual DbSet<Continentcode> Continentcodes { get; set; }

    public virtual DbSet<Countryinfo> Countryinfos { get; set; }

    public virtual DbSet<FlightPlan> FlightPlans { get; set; }

    public virtual DbSet<FlightPlanRoute> FlightPlanRoutes { get; set; }

    public virtual DbSet<GeonameEntity> GeonameEntities { get; set; }

    public virtual DbSet<IlsRunway> IlsRunways { get; set; }

    public virtual DbSet<Marker> Markers { get; set; }

    public virtual DbSet<NavSearch> NavSearches { get; set; }

    public virtual DbSet<Ndb> Ndbs { get; set; }

    public virtual DbSet<Runway> Runways { get; set; }

    public virtual DbSet<RunwaysEnd> RunwaysEnds { get; set; }

    public virtual DbSet<RunwaysStart> RunwaysStarts { get; set; }

    public virtual DbSet<SimAircraft> SimAircrafts { get; set; }

    public virtual DbSet<Transition> Transitions { get; set; }

    public virtual DbSet<TransitionsLeg> TransitionsLegs { get; set; }

    public virtual DbSet<Vor> Vors { get; set; }

    public virtual DbSet<Waypoint> Waypoints { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AircraftManufacturer>(entity =>
        {
            entity.HasKey(e => e.ManufacturerId);

            entity.ToTable("aircraft_manufacturers");

            entity.Property(e => e.ManufacturerId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("manufacturerId");
            entity.Property(e => e.ManufacturerCountry)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("manufacturerCountry");
            entity.Property(e => e.ManufacturerName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("manufacturerName");
            entity.Property(e => e.NativeName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("nativeName");
            entity.Property(e => e.PropertyValues).HasColumnName("propertyValues");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.Url).HasColumnName("url");
        });

        modelBuilder.Entity<AircraftModel>(entity =>
        {
            entity.ToTable("aircraft_models");

            entity.HasIndex(e => e.AircraftType, "IDX_aircraftType");

            entity.HasIndex(e => e.Manufacturer, "IDX_manufacturer");

            entity.Property(e => e.AircraftModelId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("aircraftModelId");
            entity.Property(e => e.AircraftFamily)
                .HasColumnType("VARCHAR(120)")
                .HasColumnName("aircraftFamily");
            entity.Property(e => e.AircraftName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("aircraftName");
            entity.Property(e => e.AircraftType)
                .IsRequired()
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("aircraftType");
            entity.Property(e => e.EngineCount).HasColumnName("engineCount");
            entity.Property(e => e.EngineFamily)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("engineFamily");
            entity.Property(e => e.EngineModels).HasColumnName("engineModels");
            entity.Property(e => e.Manufacturer)
                .IsRequired()
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("manufacturer");
            entity.Property(e => e.NativeName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("nativeName");
            entity.Property(e => e.PropertyValues).HasColumnName("propertyValues");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.Url).HasColumnName("url");

            entity.HasOne(d => d.AircraftTypeNavigation).WithMany(p => p.AircraftModels)
                .HasForeignKey(d => d.AircraftType)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.ManufacturerNavigation).WithMany(p => p.AircraftModels)
                .HasForeignKey(d => d.Manufacturer)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AircraftProperty>(entity =>
        {
            entity.HasKey(e => e.PropertyId);

            entity.ToTable("aircraft_properties");

            entity.Property(e => e.PropertyId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("propertyId");
            entity.Property(e => e.Description)
                .HasColumnType("VARCHAR(255)")
                .HasColumnName("description");
            entity.Property(e => e.PropertyName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("propertyName");
            entity.Property(e => e.PropertyType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("propertyType");
            entity.Property(e => e.Unit)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("unit");
        });

        modelBuilder.Entity<AircraftType>(entity =>
        {
            entity.ToTable("aircraft_types");

            entity.HasIndex(e => e.AircraftFamily, "IDX_aircraft_family");

            entity.HasIndex(e => e.IcaoCode, "IDX_icao_code");

            entity.HasIndex(e => e.Manufacturer, "IDX_manufacturer_id");

            entity.Property(e => e.AircraftTypeId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("aircraftTypeId");
            entity.Property(e => e.AircraftFamily)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("aircraftFamily");
            entity.Property(e => e.AircraftTypeName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("aircraftTypeName");
            entity.Property(e => e.EngineCount).HasColumnName("engineCount");
            entity.Property(e => e.EngineFamily)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("engineFamily");
            entity.Property(e => e.EngineModels).HasColumnName("engineModels");
            entity.Property(e => e.IataCode)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("iataCode");
            entity.Property(e => e.IcaoCode)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("icaoCode");
            entity.Property(e => e.Manufacturer)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("manufacturer");
            entity.Property(e => e.NativeName)
                .HasColumnType("VARCHAR(60)")
                .HasColumnName("nativeName");
            entity.Property(e => e.PropertyValues).HasColumnName("propertyValues");
            entity.Property(e => e.Tags).HasColumnName("tags");
            entity.Property(e => e.Url).HasColumnName("url");

            entity.HasOne(d => d.ManufacturerNavigation).WithMany(p => p.AircraftTypes).HasForeignKey(d => d.Manufacturer);
        });

        modelBuilder.Entity<Airport>(entity =>
        {
            entity.ToTable("airports");

            entity.HasIndex(e => e.Iata, "IDX_airport_iata");

            entity.HasIndex(e => e.Icao, "IDX_airport_icao");

            entity.HasIndex(e => e.Ident, "IDX_airport_ident");

            entity.HasIndex(e => e.AsosFrequency, "IDX_asos_frequency");

            entity.HasIndex(e => e.AtisFrequency, "IDX_atis_frequency");

            entity.HasIndex(e => e.AwosFrequency, "IDX_awos_frequency");

            entity.HasIndex(e => e.HasAvgas, "IDX_has_avgas");

            entity.HasIndex(e => e.HasJetfuel, "IDX_has_jetfuel");

            entity.HasIndex(e => e.IsClosed, "IDX_is_closed");

            entity.HasIndex(e => e.IsMilitary, "IDX_is_military");

            entity.HasIndex(e => e.Laty, "IDX_laty");

            entity.HasIndex(e => e.Lonx, "IDX_lonx");

            entity.HasIndex(e => e.TowerFrequency, "IDX_tower_frequency");

            entity.HasIndex(e => e.AirportType, "IDX_type_id");

            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportName)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("airportName");
            entity.Property(e => e.AirportType).HasColumnName("airportType");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.AsosFrequency).HasColumnName("asos_frequency");
            entity.Property(e => e.AtisFrequency).HasColumnName("atis_frequency");
            entity.Property(e => e.AwosFrequency).HasColumnName("awos_frequency");
            entity.Property(e => e.BglFilename)
                .HasColumnType("VARCHAR(300)")
                .HasColumnName("bgl_filename");
            entity.Property(e => e.BottomLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("bottom_laty");
            entity.Property(e => e.City)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("city");
            entity.Property(e => e.Country)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("country");
            entity.Property(e => e.Faa)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("faa");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Flatten).HasColumnName("flatten");
            entity.Property(e => e.FuelFlags).HasColumnName("fuel_flags");
            entity.Property(e => e.HasAvgas).HasColumnName("has_avgas");
            entity.Property(e => e.HasJetfuel).HasColumnName("has_jetfuel");
            entity.Property(e => e.HasTowerObject).HasColumnName("has_tower_object");
            entity.Property(e => e.Iata)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("iata");
            entity.Property(e => e.Icao)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("icao");
            entity.Property(e => e.Ident)
                .IsRequired()
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("ident");
            entity.Property(e => e.Is3d).HasColumnName("is_3d");
            entity.Property(e => e.IsAddon).HasColumnName("is_addon");
            entity.Property(e => e.IsClosed).HasColumnName("is_closed");
            entity.Property(e => e.IsMilitary).HasColumnName("is_military");
            entity.Property(e => e.LargestParkingGate)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("largest_parking_gate");
            entity.Property(e => e.LargestParkingRamp)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("largest_parking_ramp");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.LeftLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("left_lonx");
            entity.Property(e => e.Local)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("local");
            entity.Property(e => e.LongestRunwayHeading)
                .HasColumnType("DOUBLE")
                .HasColumnName("longest_runway_heading");
            entity.Property(e => e.LongestRunwayLength).HasColumnName("longest_runway_length");
            entity.Property(e => e.LongestRunwaySurface)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("longest_runway_surface");
            entity.Property(e => e.LongestRunwayWidth).HasColumnName("longest_runway_width");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.NumApproach).HasColumnName("num_approach");
            entity.Property(e => e.NumApron).HasColumnName("num_apron");
            entity.Property(e => e.NumCom).HasColumnName("num_com");
            entity.Property(e => e.NumHelipad).HasColumnName("num_helipad");
            entity.Property(e => e.NumJetway).HasColumnName("num_jetway");
            entity.Property(e => e.NumParkingCargo).HasColumnName("num_parking_cargo");
            entity.Property(e => e.NumParkingGaRamp).HasColumnName("num_parking_ga_ramp");
            entity.Property(e => e.NumParkingGate).HasColumnName("num_parking_gate");
            entity.Property(e => e.NumParkingMilCargo).HasColumnName("num_parking_mil_cargo");
            entity.Property(e => e.NumParkingMilCombat).HasColumnName("num_parking_mil_combat");
            entity.Property(e => e.NumRunwayEndAls).HasColumnName("num_runway_end_als");
            entity.Property(e => e.NumRunwayEndClosed).HasColumnName("num_runway_end_closed");
            entity.Property(e => e.NumRunwayEndIls).HasColumnName("num_runway_end_ils");
            entity.Property(e => e.NumRunwayEndVasi).HasColumnName("num_runway_end_vasi");
            entity.Property(e => e.NumRunwayHard).HasColumnName("num_runway_hard");
            entity.Property(e => e.NumRunwayLight).HasColumnName("num_runway_light");
            entity.Property(e => e.NumRunwaySoft).HasColumnName("num_runway_soft");
            entity.Property(e => e.NumRunwayWater).HasColumnName("num_runway_water");
            entity.Property(e => e.NumRunways).HasColumnName("num_runways");
            entity.Property(e => e.NumStarts).HasColumnName("num_starts");
            entity.Property(e => e.NumTaxiPath).HasColumnName("num_taxi_path");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("region");
            entity.Property(e => e.RightLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("right_lonx");
            entity.Property(e => e.SceneryLocalPath)
                .HasColumnType("VARCHAR(250)")
                .HasColumnName("scenery_local_path");
            entity.Property(e => e.State)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("state");
            entity.Property(e => e.TopLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("top_laty");
            entity.Property(e => e.TowerAltitude).HasColumnName("tower_altitude");
            entity.Property(e => e.TowerFrequency).HasColumnName("tower_frequency");
            entity.Property(e => e.TowerLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("tower_laty");
            entity.Property(e => e.TowerLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("tower_lonx");
            entity.Property(e => e.TransitionAltitude)
                .HasColumnType("DOUBLE")
                .HasColumnName("transition_altitude");
            entity.Property(e => e.TransitionLevel)
                .HasColumnType("DOUBLE")
                .HasColumnName("transition_level");
            entity.Property(e => e.UnicomFrequency).HasColumnName("unicom_frequency");

            entity.HasOne(d => d.AirportTypeNavigation).WithMany(p => p.Airports).HasForeignKey(d => d.AirportType);
        });

        modelBuilder.Entity<AirportType>(entity =>
        {
            entity.HasKey(e => e.TypeId);

            entity.ToTable("airport_types");

            entity.Property(e => e.TypeId).HasColumnName("typeId");
            entity.Property(e => e.AirportTypeTitle)
                .IsRequired()
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("airportTypeTitle");
            entity.Property(e => e.OrigTypeName)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("origTypeName");
        });

        modelBuilder.Entity<AirportsCom>(entity =>
        {
            entity.HasKey(e => e.ComId);

            entity.ToTable("airports_com");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id");

            entity.Property(e => e.ComId).HasColumnName("com_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.Frequency).HasColumnName("frequency");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("name");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(30)")
                .HasColumnName("type");

            entity.HasOne(d => d.Airport).WithMany(p => p.AirportsComs)
                .HasForeignKey(d => d.AirportId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AirportsLocation>(entity =>
        {
            entity.HasKey(e => e.AirportId);

            entity.ToTable("airports_location");

            entity.HasIndex(e => e.ContinentCode, "FK_cont_idx");

            entity.HasIndex(e => e.CountryId, "FK_country_idx");

            entity.HasIndex(e => e.Admin1, "Idx_admin1");

            entity.HasIndex(e => e.Admin2, "Idx_admin2");

            entity.HasIndex(e => e.Admin3, "Idx_admin3");

            entity.HasIndex(e => e.CityId, "Idx_location_id");

            entity.Property(e => e.AirportId)
                .ValueGeneratedNever()
                .HasColumnName("airportId");
            entity.Property(e => e.Admin1)
                .HasDefaultValueSql("'0'")
                .HasColumnName("admin1");
            entity.Property(e => e.Admin2)
                .HasDefaultValueSql("'0'")
                .HasColumnName("admin2");
            entity.Property(e => e.Admin3).HasColumnName("admin3");
            entity.Property(e => e.CityId)
                .HasDefaultValueSql("'0'")
                .HasColumnName("cityId");
            entity.Property(e => e.ContinentCode)
                .HasColumnType("CHARACTER(2)")
                .HasColumnName("continentCode");
            entity.Property(e => e.CountryId)
                .HasDefaultValueSql("'0'")
                .HasColumnName("countryId");
            entity.Property(e => e.GeonameCode)
                .HasColumnType("VARCHAR(45)")
                .HasColumnName("geonameCode");
            entity.Property(e => e.GeonameId)
                .HasDefaultValueSql("'0'")
                .HasColumnName("geonameId");
            entity.Property(e => e.Latitude)
                .HasColumnType("DOUBLE")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasColumnType("DOUBLE")
                .HasColumnName("longitude");

            entity.HasOne(d => d.Airport).WithOne(p => p.AirportsLocation)
                .HasForeignKey<AirportsLocation>(d => d.AirportId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Country).WithMany(p => p.AirportsLocations)
                .HasPrincipalKey(p => p.GeonameId)
                .HasForeignKey(d => d.CountryId);
        });

        modelBuilder.Entity<AirportsMsa>(entity =>
        {
            entity.HasKey(e => e.AirportMsaId);

            entity.ToTable("airports_msa");

            entity.HasIndex(e => e.AirportId, "FK_airports_id_idx");

            entity.HasIndex(e => e.AirportIdent, "IDX_airport_ident_2");

            entity.HasIndex(e => e.NavId, "IDX_nav_id");

            entity.Property(e => e.AirportMsaId).HasColumnName("airport_msa_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.BottomLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("bottom_laty");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Geometry).HasColumnName("geometry");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.LeftLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("left_lonx");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.MultipleCode)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("multiple_code");
            entity.Property(e => e.NavId).HasColumnName("nav_id");
            entity.Property(e => e.NavIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("nav_ident");
            entity.Property(e => e.NavType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("nav_type");
            entity.Property(e => e.Radius)
                .HasColumnType("DOUBLE")
                .HasColumnName("radius");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.RightLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("right_lonx");
            entity.Property(e => e.TopLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("top_laty");
            entity.Property(e => e.TrueBearing).HasColumnName("true_bearing");
            entity.Property(e => e.VorDmeOnly).HasColumnName("vor_dme_only");
            entity.Property(e => e.VorHasDme).HasColumnName("vor_has_dme");
            entity.Property(e => e.VorType)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("vor_type");

            entity.HasOne(d => d.Airport).WithMany(p => p.AirportsMsas).HasForeignKey(d => d.AirportId);
        });

        modelBuilder.Entity<Airway>(entity =>
        {
            entity.ToTable("airways");

            entity.HasIndex(e => e.AirwayName, "IDX_airway_name");

            entity.HasIndex(e => e.FromWaypointId, "from_waypoint_id");

            entity.HasIndex(e => e.ToWaypointId, "to_waypoint_id");

            entity.Property(e => e.AirwayId).HasColumnName("airway_id");
            entity.Property(e => e.AirwayFragmentNo).HasColumnName("airway_fragment_no");
            entity.Property(e => e.AirwayName)
                .IsRequired()
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("airway_name");
            entity.Property(e => e.AirwayType)
                .IsRequired()
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("airway_type");
            entity.Property(e => e.BottomLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("bottom_laty");
            entity.Property(e => e.Direction)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("direction");
            entity.Property(e => e.FromLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("from_laty");
            entity.Property(e => e.FromLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("from_lonx");
            entity.Property(e => e.FromWaypointId).HasColumnName("from_waypoint_id");
            entity.Property(e => e.LeftLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("left_lonx");
            entity.Property(e => e.MaximumAltitude).HasColumnName("maximum_altitude");
            entity.Property(e => e.MinimumAltitude).HasColumnName("minimum_altitude");
            entity.Property(e => e.RightLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("right_lonx");
            entity.Property(e => e.RouteType)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("route_type");
            entity.Property(e => e.SequenceNo).HasColumnName("sequence_no");
            entity.Property(e => e.ToLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("to_laty");
            entity.Property(e => e.ToLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("to_lonx");
            entity.Property(e => e.ToWaypointId).HasColumnName("to_waypoint_id");
            entity.Property(e => e.TopLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("top_laty");

            entity.HasOne(d => d.FromWaypoint).WithMany(p => p.AirwayFromWaypoints)
                .HasForeignKey(d => d.FromWaypointId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.ToWaypoint).WithMany(p => p.AirwayToWaypoints)
                .HasForeignKey(d => d.ToWaypointId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Approach>(entity =>
        {
            entity.ToTable("approach");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id_2");

            entity.HasIndex(e => e.RunwayEndId, "IDX_runway_end_id");

            entity.Property(e => e.ApproachId).HasColumnName("approach_id");
            entity.Property(e => e.AircraftCategory)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("aircraft_category");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.ArincName)
                .HasColumnType("VARCHAR(6)")
                .HasColumnName("arinc_name");
            entity.Property(e => e.FixAirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("fix_airport_ident");
            entity.Property(e => e.FixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("fix_ident");
            entity.Property(e => e.FixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("fix_region");
            entity.Property(e => e.FixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("fix_type");
            entity.Property(e => e.HasGpsOverlay).HasColumnName("has_gps_overlay");
            entity.Property(e => e.HasRnp).HasColumnName("has_rnp");
            entity.Property(e => e.HasVerticalAngle).HasColumnName("has_vertical_angle");
            entity.Property(e => e.Heading)
                .HasColumnType("DOUBLE")
                .HasColumnName("heading");
            entity.Property(e => e.MissedAltitude).HasColumnName("missed_altitude");
            entity.Property(e => e.RunwayEndId).HasColumnName("runway_end_id");
            entity.Property(e => e.RunwayName)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("runway_name");
            entity.Property(e => e.Suffix)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("suffix");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("type");

            entity.HasOne(d => d.Airport).WithMany(p => p.Approaches).HasForeignKey(d => d.AirportId);

            entity.HasOne(d => d.RunwayEnd).WithMany(p => p.Approaches).HasForeignKey(d => d.RunwayEndId);
        });

        modelBuilder.Entity<ApproachLeg>(entity =>
        {
            entity.ToTable("approach_leg");

            entity.HasIndex(e => e.ApproachId, "IDX_approach_id");

            entity.Property(e => e.ApproachLegId).HasColumnName("approach_leg_id");
            entity.Property(e => e.AltDescriptor)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("alt_descriptor");
            entity.Property(e => e.Altitude1)
                .HasColumnType("DOUBLE")
                .HasColumnName("altitude1");
            entity.Property(e => e.Altitude2)
                .HasColumnType("DOUBLE")
                .HasColumnName("altitude2");
            entity.Property(e => e.ApproachFixType)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("approach_fix_type");
            entity.Property(e => e.ApproachId).HasColumnName("approach_id");
            entity.Property(e => e.ArincDescrCode)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("arinc_descr_code");
            entity.Property(e => e.Course)
                .HasColumnType("DOUBLE")
                .HasColumnName("course");
            entity.Property(e => e.Distance)
                .HasColumnType("DOUBLE")
                .HasColumnName("distance");
            entity.Property(e => e.FixAirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("fix_airport_ident");
            entity.Property(e => e.FixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("fix_ident");
            entity.Property(e => e.FixLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("fix_laty");
            entity.Property(e => e.FixLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("fix_lonx");
            entity.Property(e => e.FixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("fix_region");
            entity.Property(e => e.FixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("fix_type");
            entity.Property(e => e.IsFlyover).HasColumnName("is_flyover");
            entity.Property(e => e.IsMissed).HasColumnName("is_missed");
            entity.Property(e => e.IsTrueCourse).HasColumnName("is_true_course");
            entity.Property(e => e.RecommendedFixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("recommended_fix_ident");
            entity.Property(e => e.RecommendedFixLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("recommended_fix_laty");
            entity.Property(e => e.RecommendedFixLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("recommended_fix_lonx");
            entity.Property(e => e.RecommendedFixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("recommended_fix_region");
            entity.Property(e => e.RecommendedFixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("recommended_fix_type");
            entity.Property(e => e.Rho)
                .HasColumnType("DOUBLE")
                .HasColumnName("rho");
            entity.Property(e => e.Rnp)
                .HasColumnType("DOUBLE")
                .HasColumnName("rnp");
            entity.Property(e => e.SpeedLimit).HasColumnName("speed_limit");
            entity.Property(e => e.SpeedLimitType)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("speed_limit_type");
            entity.Property(e => e.Theta)
                .HasColumnType("DOUBLE")
                .HasColumnName("theta");
            entity.Property(e => e.Time)
                .HasColumnType("DOUBLE")
                .HasColumnName("time");
            entity.Property(e => e.TurnDirection)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("turn_direction");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("type");
            entity.Property(e => e.VerticalAngle)
                .HasColumnType("DOUBLE")
                .HasColumnName("vertical_angle");
        });

        modelBuilder.Entity<Continentcode>(entity =>
        {
            entity.HasKey(e => e.Code);

            entity.ToTable("continentcodes");

            entity.HasIndex(e => e.GeonameId, "geonameId");

            entity.HasIndex(e => e.Name, "name");

            entity.Property(e => e.Code)
                .HasColumnType("CHARACTER(2)")
                .HasColumnName("code");
            entity.Property(e => e.GeonameId).HasColumnName("geonameId");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("name");
        });

        modelBuilder.Entity<Countryinfo>(entity =>
        {
            entity.HasKey(e => e.IsoAlpha2);

            entity.ToTable("countryinfo");

            entity.HasIndex(e => e.GeonameId, "FK_country_geonameId");

            entity.HasIndex(e => e.GeonameId, "UX_countryinfo_geonameId").IsUnique();

            entity.HasIndex(e => e.Continent, "continent");

            entity.HasIndex(e => e.FipsCode, "fips_code");

            entity.HasIndex(e => e.IsoAlpha2, "iso_alpha2");

            entity.HasIndex(e => e.IsoAlpha3, "iso_alpha3");

            entity.HasIndex(e => e.IsoNumeric, "iso_numeric");

            entity.HasIndex(e => e.Name, "name_2");

            entity.Property(e => e.IsoAlpha2)
                .HasColumnType("CHARACTER(2)")
                .HasColumnName("iso_alpha2");
            entity.Property(e => e.Areainsqkm)
                .HasColumnType("DOUBLE")
                .HasColumnName("areainsqkm");
            entity.Property(e => e.Capital)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("capital");
            entity.Property(e => e.Continent)
                .HasColumnType("CHARACTER(2)")
                .HasColumnName("continent");
            entity.Property(e => e.Currency)
                .HasColumnType("CHARACTER(3)")
                .HasColumnName("currency");
            entity.Property(e => e.CurrencyName)
                .HasColumnType("CHARACTER(20)")
                .HasColumnName("currencyName");
            entity.Property(e => e.EquivalentFipsCode)
                .HasColumnType("CHARACTER(10)")
                .HasColumnName("equivalentFipsCode");
            entity.Property(e => e.FipsCode)
                .HasColumnType("VARCHAR(3)")
                .HasColumnName("fips_code");
            entity.Property(e => e.GeonameId)
                .HasDefaultValueSql("'0'")
                .HasColumnName("geonameId");
            entity.Property(e => e.IsoAlpha3)
                .HasColumnType("CHARACTER(3)")
                .HasColumnName("iso_alpha3");
            entity.Property(e => e.IsoNumeric).HasColumnName("iso_numeric");
            entity.Property(e => e.Languages)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("languages");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("name");
            entity.Property(e => e.Neighbours)
                .HasColumnType("CHARACTER(100)")
                .HasColumnName("neighbours");
            entity.Property(e => e.Phone).HasColumnType("CHARACTER(25)");
            entity.Property(e => e.Population).HasColumnName("population");
            entity.Property(e => e.PostalCodeFormat)
                .HasColumnType("VARCHAR(100)")
                .HasColumnName("postalCodeFormat");
            entity.Property(e => e.PostalCodeRegex)
                .HasColumnType("VARCHAR(255)")
                .HasColumnName("postalCodeRegex");
            entity.Property(e => e.Tld)
                .HasColumnType("CHARACTER(3)")
                .HasColumnName("tld");

            entity.HasOne(d => d.Geoname).WithOne(p => p.Countryinfo)
                .HasForeignKey<Countryinfo>(d => d.GeonameId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<FlightPlan>(entity =>
        {
            entity.ToTable("flight_plans");

            entity.HasIndex(e => e.AircraftModelId, "IDX_aircraft_id");

            entity.HasIndex(e => e.EndAirportId, "IDX_airport_end");

            entity.HasIndex(e => e.StartAirportId, "IDX_airport_start");

            entity.Property(e => e.FlightPlanId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("flightPlanId");
            entity.Property(e => e.AircraftCrashed)
                .HasDefaultValueSql("'0'")
                .HasColumnType("TINYINT")
                .HasColumnName("aircraftCrashed");
            entity.Property(e => e.AircraftModelId)
                .IsRequired()
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("aircraftModelId");
            entity.Property(e => e.Comments).HasColumnName("comments");
            entity.Property(e => e.CruiseAltitude)
                .HasDefaultValueSql("'5000'")
                .HasColumnName("cruise_altitude");
            entity.Property(e => e.DateCreated)
                .HasColumnType("DATETIME")
                .HasColumnName("dateCreated");
            entity.Property(e => e.DateFlown)
                .HasColumnType("DATETIME")
                .HasColumnName("dateFlown");
            entity.Property(e => e.DistanceNm)
                .HasColumnType("DECIMAL")
                .HasColumnName("distanceNM");
            entity.Property(e => e.EndAirportId).HasColumnName("endAirportId");
            entity.Property(e => e.EstFlightTime)
                .HasDefaultValueSql("'00:00:00'")
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("estFlightTime");
            entity.Property(e => e.LastModified)
                .HasColumnType("DATETIME")
                .HasColumnName("lastModified");
            entity.Property(e => e.StartAirportId).HasColumnName("startAirportId");

            entity.HasOne(d => d.AircraftModel).WithMany(p => p.FlightPlans)
                .HasForeignKey(d => d.AircraftModelId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.EndAirport).WithMany(p => p.FlightPlanEndAirports).HasForeignKey(d => d.EndAirportId);

            entity.HasOne(d => d.StartAirport).WithMany(p => p.FlightPlanStartAirports).HasForeignKey(d => d.StartAirportId);
        });

        modelBuilder.Entity<FlightPlanRoute>(entity =>
        {
            entity.HasKey(e => e.FpStepId);

            entity.ToTable("flight_plan_routes");

            entity.Property(e => e.FpStepId)
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("fp_step_id");
            entity.Property(e => e.AirwayId).HasColumnName("airwayId");
            entity.Property(e => e.FlightPlanId)
                .IsRequired()
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("flightPlanId");
            entity.Property(e => e.SequenceNumber).HasColumnName("sequenceNumber");
            entity.Property(e => e.WaypointId).HasColumnName("waypointId");

            entity.HasOne(d => d.Airway).WithMany(p => p.FlightPlanRoutes).HasForeignKey(d => d.AirwayId);

            entity.HasOne(d => d.FlightPlan).WithMany(p => p.FlightPlanRoutes).HasForeignKey(d => d.FlightPlanId);

            entity.HasOne(d => d.Waypoint).WithMany(p => p.FlightPlanRoutes)
                .HasForeignKey(d => d.WaypointId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<GeonameEntity>(entity =>
        {
            entity.HasKey(e => e.GeonameId);

            entity.ToTable("geoname_entities");

            entity.HasIndex(e => e.Admin1, "admin1");

            entity.HasIndex(e => e.Asciiname, "asciiname");

            entity.HasIndex(e => e.Country, "country");

            entity.HasIndex(e => e.Fclass, "fclass");

            entity.HasIndex(e => e.Fcode, "fcode");

            entity.HasIndex(e => e.Latitude, "lat");

            entity.HasIndex(e => e.Longitude, "lon");

            entity.HasIndex(e => e.Name, "name_3");

            entity.Property(e => e.GeonameId)
                .ValueGeneratedNever()
                .HasColumnName("geonameId");
            entity.Property(e => e.Admin1)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("admin1");
            entity.Property(e => e.Admin2)
                .HasColumnType("VARCHAR(80)")
                .HasColumnName("admin2");
            entity.Property(e => e.Admin3)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("admin3");
            entity.Property(e => e.Admin4)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("admin4");
            entity.Property(e => e.Admin5)
                .HasColumnType("VARCHAR(20)")
                .HasColumnName("admin5");
            entity.Property(e => e.Alternatenames).HasColumnName("alternatenames");
            entity.Property(e => e.Asciiname)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("asciiname");
            entity.Property(e => e.Cc2)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("cc2");
            entity.Property(e => e.Country)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("country");
            entity.Property(e => e.Elevation)
                .HasDefaultValueSql("'0'")
                .HasColumnType("BIGINT")
                .HasColumnName("elevation");
            entity.Property(e => e.Fclass)
                .HasColumnType("CHARACTER(1)")
                .HasColumnName("fclass");
            entity.Property(e => e.Fcode)
                .HasColumnType("CHARACTER(7)")
                .HasColumnName("fcode");
            entity.Property(e => e.Gtopo30).HasColumnName("gtopo30");
            entity.Property(e => e.Latitude)
                .HasColumnType("DOUBLE")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasColumnType("DOUBLE")
                .HasColumnName("longitude");
            entity.Property(e => e.Moddate)
                .HasColumnType("VARCHAR(40)")
                .HasColumnName("moddate");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(200)")
                .HasColumnName("name");
            entity.Property(e => e.Population)
                .HasDefaultValueSql("'0'")
                .HasColumnType("BIGINT")
                .HasColumnName("population");
            entity.Property(e => e.Timezone)
                .HasColumnType("VARCHAR(40)")
                .HasColumnName("timezone");
        });

        modelBuilder.Entity<IlsRunway>(entity =>
        {
            entity.HasKey(e => e.IlsId);

            entity.ToTable("ils_runways");

            entity.HasIndex(e => e.LocAirportIdent, "IDX_airport_ident_3");

            entity.HasIndex(e => e.Ident, "IDX_ident");

            entity.HasIndex(e => e.LocRunwayEndId, "IDX_loc_runway_end_id");

            entity.Property(e => e.IlsId).HasColumnName("ils_id");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.DmeAltitude).HasColumnName("dme_altitude");
            entity.Property(e => e.DmeLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("dme_laty");
            entity.Property(e => e.DmeLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("dme_lonx");
            entity.Property(e => e.DmeRange).HasColumnName("dme_range");
            entity.Property(e => e.End1Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("end1_laty");
            entity.Property(e => e.End1Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("end1_lonx");
            entity.Property(e => e.End2Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("end2_laty");
            entity.Property(e => e.End2Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("end2_lonx");
            entity.Property(e => e.EndMidLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("end_mid_laty");
            entity.Property(e => e.EndMidLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("end_mid_lonx");
            entity.Property(e => e.Frequency).HasColumnName("frequency");
            entity.Property(e => e.GsAltitude).HasColumnName("gs_altitude");
            entity.Property(e => e.GsLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("gs_laty");
            entity.Property(e => e.GsLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("gs_lonx");
            entity.Property(e => e.GsPitch)
                .HasColumnType("DOUBLE")
                .HasColumnName("gs_pitch");
            entity.Property(e => e.GsRange).HasColumnName("gs_range");
            entity.Property(e => e.HasBackcourse).HasColumnName("has_backcourse");
            entity.Property(e => e.Ident)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.IlsName)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("ils_name");
            entity.Property(e => e.IlsType)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("ils_type");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.LocAirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("loc_airport_ident");
            entity.Property(e => e.LocHeading)
                .HasColumnType("DOUBLE")
                .HasColumnName("loc_heading");
            entity.Property(e => e.LocRunwayEndId).HasColumnName("loc_runway_end_id");
            entity.Property(e => e.LocRunwayName)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("loc_runway_name");
            entity.Property(e => e.LocWidth)
                .HasColumnType("DOUBLE")
                .HasColumnName("loc_width");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.PerfIndicator)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("perf_indicator");
            entity.Property(e => e.Provider)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("provider");
            entity.Property(e => e.Range).HasColumnName("range");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");

            entity.HasOne(d => d.LocRunwayEnd).WithMany(p => p.IlsRunways).HasForeignKey(d => d.LocRunwayEndId);
        });

        modelBuilder.Entity<Marker>(entity =>
        {
            entity.ToTable("markers");

            entity.Property(e => e.MarkerId).HasColumnName("marker_id");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Heading)
                .HasColumnType("DOUBLE")
                .HasColumnName("heading");
            entity.Property(e => e.Ident)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("type");
        });

        modelBuilder.Entity<NavSearch>(entity =>
        {
            entity.ToTable("nav_search");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id_3");

            entity.HasIndex(e => e.AirportIdent, "IDX_airport_ident_4");

            entity.HasIndex(e => e.Ident, "IDX_nav_ident");

            entity.HasIndex(e => e.Name, "IDX_nav_name");

            entity.HasIndex(e => e.NdbId, "IDX_ndb_id");

            entity.HasIndex(e => e.VorId, "IDX_vor_id");

            entity.HasIndex(e => e.WaypointNavId, "IDX_waypoint_nav_id");

            entity.Property(e => e.NavSearchId).HasColumnName("nav_search_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.ArincType)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("arinc_type");
            entity.Property(e => e.BglFilename)
                .HasColumnType("VARCHAR(300)")
                .HasColumnName("bgl_filename");
            entity.Property(e => e.Channel)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("channel");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Frequency).HasColumnName("frequency");
            entity.Property(e => e.Ident)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("name");
            entity.Property(e => e.NavType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("nav_type");
            entity.Property(e => e.NdbId).HasColumnName("ndb_id");
            entity.Property(e => e.Range).HasColumnName("range");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.SceneryLocalPath)
                .HasColumnType("VARCHAR(250)")
                .HasColumnName("scenery_local_path");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("type");
            entity.Property(e => e.VorId).HasColumnName("vor_id");
            entity.Property(e => e.WaypointId).HasColumnName("waypoint_id");
            entity.Property(e => e.WaypointNavId).HasColumnName("waypoint_nav_id");
            entity.Property(e => e.WaypointNumJetAirway).HasColumnName("waypoint_num_jet_airway");
            entity.Property(e => e.WaypointNumVictorAirway).HasColumnName("waypoint_num_victor_airway");
        });

        modelBuilder.Entity<Ndb>(entity =>
        {
            entity.ToTable("ndb");

            entity.Property(e => e.NdbId).HasColumnName("ndb_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Frequency).HasColumnName("frequency");
            entity.Property(e => e.Ident)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("name");
            entity.Property(e => e.Range).HasColumnName("range");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Runway>(entity =>
        {
            entity.ToTable("runways");

            entity.HasIndex(e => e.PrimaryEndId, "FK_runway_end_id_idx");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id_4");

            entity.Property(e => e.RunwayId).HasColumnName("runway_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.CenterLight)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("center_light");
            entity.Property(e => e.EdgeLight)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("edge_light");
            entity.Property(e => e.HasCenterRed).HasColumnName("has_center_red");
            entity.Property(e => e.Heading)
                .HasColumnType("DOUBLE")
                .HasColumnName("heading");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Length)
                .HasColumnType("DOUBLE")
                .HasColumnName("length");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MarkingFlags).HasColumnName("marking_flags");
            entity.Property(e => e.PatternAltitude).HasColumnName("pattern_altitude");
            entity.Property(e => e.PrimaryEndId).HasColumnName("primary_end_id");
            entity.Property(e => e.PrimaryLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("primary_laty");
            entity.Property(e => e.PrimaryLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("primary_lonx");
            entity.Property(e => e.SecondaryEndId).HasColumnName("secondary_end_id");
            entity.Property(e => e.SecondaryLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("secondary_laty");
            entity.Property(e => e.SecondaryLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("secondary_lonx");
            entity.Property(e => e.Shoulder)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("shoulder");
            entity.Property(e => e.Smoothness)
                .HasColumnType("DOUBLE")
                .HasColumnName("smoothness");
            entity.Property(e => e.Surface)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("surface");
            entity.Property(e => e.Width)
                .HasColumnType("DOUBLE")
                .HasColumnName("width");

            entity.HasOne(d => d.Airport).WithMany(p => p.Runways)
                .HasForeignKey(d => d.AirportId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.PrimaryEnd).WithMany(p => p.Runways)
                .HasForeignKey(d => d.PrimaryEndId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<RunwaysEnd>(entity =>
        {
            entity.HasKey(e => e.RunwayEndId);

            entity.ToTable("runways_end");

            entity.HasIndex(e => e.Heading, "IDX_heading");

            entity.HasIndex(e => e.IlsIdent, "IDX_ils_ident");

            entity.Property(e => e.RunwayEndId).HasColumnName("runway_end_id");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.AppLightSystemType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("app_light_system_type");
            entity.Property(e => e.BlastPad)
                .HasColumnType("DOUBLE")
                .HasColumnName("blast_pad");
            entity.Property(e => e.EndType)
                .IsRequired()
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("end_type");
            entity.Property(e => e.HasClosedMarkings).HasColumnName("has_closed_markings");
            entity.Property(e => e.HasEndLights).HasColumnName("has_end_lights");
            entity.Property(e => e.HasReils).HasColumnName("has_reils");
            entity.Property(e => e.HasStolMarkings).HasColumnName("has_stol_markings");
            entity.Property(e => e.HasTouchdownLights).HasColumnName("has_touchdown_lights");
            entity.Property(e => e.Heading)
                .HasColumnType("DOUBLE")
                .HasColumnName("heading");
            entity.Property(e => e.IlsIdent)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("ils_ident");
            entity.Property(e => e.IsLanding).HasColumnName("is_landing");
            entity.Property(e => e.IsPattern)
                .IsRequired()
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("is_pattern");
            entity.Property(e => e.IsTakeoff).HasColumnName("is_takeoff");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.LeftVasiPitch)
                .HasColumnType("DOUBLE")
                .HasColumnName("left_vasi_pitch");
            entity.Property(e => e.LeftVasiType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("left_vasi_type");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("name");
            entity.Property(e => e.NumStrobes).HasColumnName("num_strobes");
            entity.Property(e => e.OffsetThreshold)
                .HasColumnType("DOUBLE")
                .HasColumnName("offset_threshold");
            entity.Property(e => e.Overrun)
                .HasColumnType("DOUBLE")
                .HasColumnName("overrun");
            entity.Property(e => e.RightVasiPitch)
                .HasColumnType("DOUBLE")
                .HasColumnName("right_vasi_pitch");
            entity.Property(e => e.RightVasiType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("right_vasi_type");
        });

        modelBuilder.Entity<RunwaysStart>(entity =>
        {
            entity.HasKey(e => e.StartId);

            entity.ToTable("runways_start");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id_5");

            entity.Property(e => e.StartId).HasColumnName("start_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.Heading)
                .HasColumnType("DOUBLE")
                .HasColumnName("heading");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.Number).HasColumnName("number");
            entity.Property(e => e.RunwayEndId).HasColumnName("runway_end_id");
            entity.Property(e => e.RunwayName)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("runway_name");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("type");

            entity.HasOne(d => d.Airport).WithMany(p => p.RunwaysStarts)
                .HasForeignKey(d => d.AirportId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<SimAircraft>(entity =>
        {
            entity.HasKey(e => e.SimPlaneId);

            entity.ToTable("sim_aircraft");

            entity.HasIndex(e => e.AircraftId, "FK_aircraft_idm_idx");

            entity.Property(e => e.SimPlaneId).HasColumnName("simPlaneId");
            entity.Property(e => e.AircraftId)
                .IsRequired()
                .HasColumnType("VARCHAR(36)")
                .HasColumnName("aircraftId");

            entity.HasOne(d => d.Aircraft).WithMany(p => p.SimAircrafts)
                .HasForeignKey(d => d.AircraftId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Transition>(entity =>
        {
            entity.ToTable("transitions");

            entity.HasIndex(e => e.ApproachId, "IDX_approach_id_2");

            entity.HasIndex(e => e.FixAirportIdent, "IDX_fix_airport_ident");

            entity.HasIndex(e => e.FixIdent, "IDX_fix_ident");

            entity.Property(e => e.TransitionId).HasColumnName("transition_id");
            entity.Property(e => e.AircraftCategory)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("aircraft_category");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.ApproachId).HasColumnName("approach_id");
            entity.Property(e => e.DmeAirportIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("dme_airport_ident");
            entity.Property(e => e.DmeDistance).HasColumnName("dme_distance");
            entity.Property(e => e.DmeIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("dme_ident");
            entity.Property(e => e.DmeRadial)
                .HasColumnType("DOUBLE")
                .HasColumnName("dme_radial");
            entity.Property(e => e.DmeRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("dme_region");
            entity.Property(e => e.FixAirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("fix_airport_ident");
            entity.Property(e => e.FixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("fix_ident");
            entity.Property(e => e.FixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("fix_region");
            entity.Property(e => e.FixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("fix_type");
            entity.Property(e => e.TransitionType)
                .IsRequired()
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("transition_type");
        });

        modelBuilder.Entity<TransitionsLeg>(entity =>
        {
            entity.HasKey(e => e.TransitionLegId);

            entity.ToTable("transitions_leg");

            entity.HasIndex(e => e.FixAirportIdent, "IDX_fix_airport_ident_2");

            entity.HasIndex(e => e.FixIdent, "IDX_fix_ident_2");

            entity.HasIndex(e => e.TransitionId, "IDX_transition_id");

            entity.Property(e => e.TransitionLegId).HasColumnName("transition_leg_id");
            entity.Property(e => e.AltDescriptor)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("alt_descriptor");
            entity.Property(e => e.Altitude1)
                .HasColumnType("DOUBLE")
                .HasColumnName("altitude1");
            entity.Property(e => e.Altitude2)
                .HasColumnType("DOUBLE")
                .HasColumnName("altitude2");
            entity.Property(e => e.ApproachFixType)
                .HasColumnType("VARCHAR(1)")
                .HasColumnName("approach_fix_type");
            entity.Property(e => e.ArincDescrCode)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("arinc_descr_code");
            entity.Property(e => e.Course)
                .HasColumnType("DOUBLE")
                .HasColumnName("course");
            entity.Property(e => e.Distance)
                .HasColumnType("DOUBLE")
                .HasColumnName("distance");
            entity.Property(e => e.FixAirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("fix_airport_ident");
            entity.Property(e => e.FixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("fix_ident");
            entity.Property(e => e.FixLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("fix_laty");
            entity.Property(e => e.FixLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("fix_lonx");
            entity.Property(e => e.FixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("fix_region");
            entity.Property(e => e.FixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("fix_type");
            entity.Property(e => e.IsFlyover).HasColumnName("is_flyover");
            entity.Property(e => e.IsTrueCourse).HasColumnName("is_true_course");
            entity.Property(e => e.RecommendedFixIdent)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("recommended_fix_ident");
            entity.Property(e => e.RecommendedFixLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("recommended_fix_laty");
            entity.Property(e => e.RecommendedFixLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("recommended_fix_lonx");
            entity.Property(e => e.RecommendedFixRegion)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("recommended_fix_region");
            entity.Property(e => e.RecommendedFixType)
                .HasColumnType("VARCHAR(25)")
                .HasColumnName("recommended_fix_type");
            entity.Property(e => e.Rho)
                .HasColumnType("DOUBLE")
                .HasColumnName("rho");
            entity.Property(e => e.Rnp)
                .HasColumnType("DOUBLE")
                .HasColumnName("rnp");
            entity.Property(e => e.SpeedLimit).HasColumnName("speed_limit");
            entity.Property(e => e.SpeedLimitType)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("speed_limit_type");
            entity.Property(e => e.Theta)
                .HasColumnType("DOUBLE")
                .HasColumnName("theta");
            entity.Property(e => e.Time)
                .HasColumnType("DOUBLE")
                .HasColumnName("time");
            entity.Property(e => e.TransitionId).HasColumnName("transition_id");
            entity.Property(e => e.TurnDirection)
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("turn_direction");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("VARCHAR(10)")
                .HasColumnName("type");
            entity.Property(e => e.VerticalAngle)
                .HasColumnType("DOUBLE")
                .HasColumnName("vertical_angle");

            entity.HasOne(d => d.Transition).WithMany(p => p.TransitionsLegs)
                .HasForeignKey(d => d.TransitionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Vor>(entity =>
        {
            entity.ToTable("vor");

            entity.Property(e => e.VorId).HasColumnName("vor_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.Altitude).HasColumnName("altitude");
            entity.Property(e => e.Channel)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("channel");
            entity.Property(e => e.DmeAltitude).HasColumnName("dme_altitude");
            entity.Property(e => e.DmeLaty)
                .HasColumnType("DOUBLE")
                .HasColumnName("dme_laty");
            entity.Property(e => e.DmeLonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("dme_lonx");
            entity.Property(e => e.DmeOnly).HasColumnName("dme_only");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Frequency).HasColumnName("frequency");
            entity.Property(e => e.Ident)
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.Name)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("name");
            entity.Property(e => e.Range).HasColumnName("range");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.Type)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("type");
        });

        modelBuilder.Entity<Waypoint>(entity =>
        {
            entity.ToTable("waypoints");

            entity.HasIndex(e => e.AirportId, "IDX_airport_id_6");

            entity.HasIndex(e => e.Ident, "IDX_ident_2");

            entity.HasIndex(e => e.NavId, "IDX_nav_id_2");

            entity.Property(e => e.WaypointId).HasColumnName("waypoint_id");
            entity.Property(e => e.AirportId).HasColumnName("airport_id");
            entity.Property(e => e.AirportIdent)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("airport_ident");
            entity.Property(e => e.ArincType)
                .HasColumnType("VARCHAR(4)")
                .HasColumnName("arinc_type");
            entity.Property(e => e.Artificial).HasColumnName("artificial");
            entity.Property(e => e.FileId).HasColumnName("file_id");
            entity.Property(e => e.Ident)
                .IsRequired()
                .HasColumnType("VARCHAR(5)")
                .HasColumnName("ident");
            entity.Property(e => e.Laty)
                .HasColumnType("DOUBLE")
                .HasColumnName("laty");
            entity.Property(e => e.Lonx)
                .HasColumnType("DOUBLE")
                .HasColumnName("lonx");
            entity.Property(e => e.MagVar)
                .HasColumnType("DOUBLE")
                .HasColumnName("mag_var");
            entity.Property(e => e.NavId).HasColumnName("nav_id");
            entity.Property(e => e.NumJetAirway).HasColumnName("num_jet_airway");
            entity.Property(e => e.NumVictorAirway).HasColumnName("num_victor_airway");
            entity.Property(e => e.Region)
                .HasColumnType("VARCHAR(2)")
                .HasColumnName("region");
            entity.Property(e => e.WaypointName)
                .HasColumnType("VARCHAR(50)")
                .HasColumnName("waypoint_name");
            entity.Property(e => e.WaypointType)
                .HasColumnType("VARCHAR(15)")
                .HasColumnName("waypoint_type");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}