// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AircraftType
{
    public string AircraftTypeId { get; set; }

    public string AircraftFamily { get; set; }

    public int? EngineCount { get; set; }

    public string EngineFamily { get; set; }

    public string EngineModels { get; set; }

    public string IataCode { get; set; }

    public string IcaoCode { get; set; }

    public string Manufacturer { get; set; }

    public string AircraftTypeName { get; set; }

    public string NativeName { get; set; }

    public string PropertyValues { get; set; }

    public string Tags { get; set; }

    public string Url { get; set; }

    public virtual ICollection<AircraftModel> AircraftModels { get; set; } = new List<AircraftModel>();

    public virtual AircraftManufacturer ManufacturerNavigation { get; set; }
}