// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AircraftModel
{
    public string AircraftModelId { get; set; }

    public string AircraftFamily { get; set; }

    public string AircraftType { get; set; }

    public int? EngineCount { get; set; }

    public string EngineFamily { get; set; }

    public string EngineModels { get; set; }

    public string Manufacturer { get; set; }

    public string AircraftName { get; set; }

    public string NativeName { get; set; }

    public string PropertyValues { get; set; }

    public string Tags { get; set; }

    public string Url { get; set; }

    public virtual AircraftType AircraftTypeNavigation { get; set; }

    public virtual ICollection<FlightPlan> FlightPlans { get; set; } = new List<FlightPlan>();

    public virtual AircraftManufacturer ManufacturerNavigation { get; set; }

    public virtual ICollection<SimAircraft> SimAircrafts { get; set; } = new List<SimAircraft>();
}