// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AircraftManufacturer
{
    public string ManufacturerId { get; set; }

    public string ManufacturerCountry { get; set; }

    public string ManufacturerName { get; set; }

    public string NativeName { get; set; }

    public string PropertyValues { get; set; }

    public string Tags { get; set; }

    public string Url { get; set; }

    public virtual ICollection<AircraftModel> AircraftModels { get; set; } = new List<AircraftModel>();

    public virtual ICollection<AircraftType> AircraftTypes { get; set; } = new List<AircraftType>();
}