// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AirportsMsa
{
    public int AirportMsaId { get; set; }

    public int FileId { get; set; }

    public int? AirportId { get; set; }

    public string AirportIdent { get; set; }

    public int? NavId { get; set; }

    public string NavIdent { get; set; }

    public string NavType { get; set; }

    public string VorType { get; set; }

    public int? VorDmeOnly { get; set; }

    public int? VorHasDme { get; set; }

    public string Region { get; set; }

    public string MultipleCode { get; set; }

    public int? TrueBearing { get; set; }

    public double? MagVar { get; set; }

    public double? LeftLonx { get; set; }

    public double? TopLaty { get; set; }

    public double? RightLonx { get; set; }

    public double? BottomLaty { get; set; }

    public double Radius { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public byte[] Geometry { get; set; }

    public virtual Airport Airport { get; set; }
}