// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AirportsCom
{
    public int ComId { get; set; }

    public int AirportId { get; set; }

    public string Type { get; set; }

    public int Frequency { get; set; }

    public string Name { get; set; }

    public virtual Airport Airport { get; set; }
}