// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AirportsLocation
{
    public int AirportId { get; set; }

    public int? GeonameId { get; set; }

    public int? CityId { get; set; }

    public string ContinentCode { get; set; }

    public int? CountryId { get; set; }

    public int? Admin1 { get; set; }

    public int? Admin2 { get; set; }

    public int? Admin3 { get; set; }

    public string GeonameCode { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public virtual Airport Airport { get; set; }

    public virtual Countryinfo Country { get; set; }
}