// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Airport
{
    public int AirportId { get; set; }

    public int FileId { get; set; }

    public string Ident { get; set; }

    public string Icao { get; set; }

    public string Iata { get; set; }

    public string Faa { get; set; }

    public string Local { get; set; }

    public string AirportName { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string Region { get; set; }

    public int? Flatten { get; set; }

    public int? AirportType { get; set; }

    public int FuelFlags { get; set; }

    public int HasAvgas { get; set; }

    public int HasJetfuel { get; set; }

    public int HasTowerObject { get; set; }

    public int? TowerFrequency { get; set; }

    public int? AtisFrequency { get; set; }

    public int? AwosFrequency { get; set; }

    public int? AsosFrequency { get; set; }

    public int? UnicomFrequency { get; set; }

    public int IsClosed { get; set; }

    public int IsMilitary { get; set; }

    public int IsAddon { get; set; }

    public int NumCom { get; set; }

    public int NumParkingGate { get; set; }

    public int NumParkingGaRamp { get; set; }

    public int NumParkingCargo { get; set; }

    public int NumParkingMilCargo { get; set; }

    public int NumParkingMilCombat { get; set; }

    public int NumApproach { get; set; }

    public int NumRunwayHard { get; set; }

    public int NumRunwaySoft { get; set; }

    public int NumRunwayWater { get; set; }

    public int NumRunwayLight { get; set; }

    public int NumRunwayEndClosed { get; set; }

    public int NumRunwayEndVasi { get; set; }

    public int NumRunwayEndAls { get; set; }

    public int? NumRunwayEndIls { get; set; }

    public int NumApron { get; set; }

    public int NumTaxiPath { get; set; }

    public int NumHelipad { get; set; }

    public int NumJetway { get; set; }

    public int NumStarts { get; set; }

    public int LongestRunwayLength { get; set; }

    public int LongestRunwayWidth { get; set; }

    public double LongestRunwayHeading { get; set; }

    public string LongestRunwaySurface { get; set; }

    public int NumRunways { get; set; }

    public string LargestParkingRamp { get; set; }

    public string LargestParkingGate { get; set; }

    public int Rating { get; set; }

    public int Is3d { get; set; }

    public string SceneryLocalPath { get; set; }

    public string BglFilename { get; set; }

    public double LeftLonx { get; set; }

    public double TopLaty { get; set; }

    public double RightLonx { get; set; }

    public double BottomLaty { get; set; }

    public double MagVar { get; set; }

    public int? TowerAltitude { get; set; }

    public double? TowerLonx { get; set; }

    public double? TowerLaty { get; set; }

    public double? TransitionAltitude { get; set; }

    public double? TransitionLevel { get; set; }

    public int Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual AirportType AirportTypeNavigation { get; set; }

    public virtual ICollection<AirportsCom> AirportsComs { get; set; } = new List<AirportsCom>();

    public virtual AirportsLocation AirportsLocation { get; set; }

    public virtual ICollection<AirportsMsa> AirportsMsas { get; set; } = new List<AirportsMsa>();

    public virtual ICollection<Approach> Approaches { get; set; } = new List<Approach>();

    public virtual ICollection<FlightPlan> FlightPlanEndAirports { get; set; } = new List<FlightPlan>();

    public virtual ICollection<FlightPlan> FlightPlanStartAirports { get; set; } = new List<FlightPlan>();

    public virtual ICollection<Runway> Runways { get; set; } = new List<Runway>();

    public virtual ICollection<RunwaysStart> RunwaysStarts { get; set; } = new List<RunwaysStart>();

}