// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class AirportType
{
    public int TypeId { get; set; }

    public string AirportTypeTitle { get; set; }

    public string OrigTypeName { get; set; }

    public virtual ICollection<Airport> Airports { get; set; } = new List<Airport>();
}