// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Airway
{
    public int AirwayId { get; set; }

    public string AirwayName { get; set; }

    public string AirwayType { get; set; }

    public string RouteType { get; set; }

    public int AirwayFragmentNo { get; set; }

    public int SequenceNo { get; set; }

    public int FromWaypointId { get; set; }

    public int ToWaypointId { get; set; }

    public string Direction { get; set; }

    public int? MinimumAltitude { get; set; }

    public int? MaximumAltitude { get; set; }

    public double LeftLonx { get; set; }

    public double TopLaty { get; set; }

    public double RightLonx { get; set; }

    public double BottomLaty { get; set; }

    public double FromLonx { get; set; }

    public double FromLaty { get; set; }

    public double ToLonx { get; set; }

    public double ToLaty { get; set; }

    public virtual ICollection<FlightPlanRoute> FlightPlanRoutes { get; set; } = new List<FlightPlanRoute>();

    public virtual Waypoint FromWaypoint { get; set; }

    public virtual Waypoint ToWaypoint { get; set; }
}