// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Approach
{
    public int ApproachId { get; set; }

    public int? AirportId { get; set; }

    public int? RunwayEndId { get; set; }

    public string ArincName { get; set; }

    public string AirportIdent { get; set; }

    public string RunwayName { get; set; }

    public string Type { get; set; }

    public string Suffix { get; set; }

    public int HasGpsOverlay { get; set; }

    public int? HasVerticalAngle { get; set; }

    public int? HasRnp { get; set; }

    public string FixType { get; set; }

    public string FixIdent { get; set; }

    public string FixRegion { get; set; }

    public string FixAirportIdent { get; set; }

    public string AircraftCategory { get; set; }

    public int? Altitude { get; set; }

    public double? Heading { get; set; }

    public int? MissedAltitude { get; set; }

    public virtual Airport Airport { get; set; }

    public virtual RunwaysEnd RunwayEnd { get; set; }
}