// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class ApproachLeg
{
    public int ApproachLegId { get; set; }

    public int ApproachId { get; set; }

    public int IsMissed { get; set; }

    public string Type { get; set; }

    public string ArincDescrCode { get; set; }

    public string ApproachFixType { get; set; }

    public string AltDescriptor { get; set; }

    public string TurnDirection { get; set; }

    public double? Rnp { get; set; }

    public string FixType { get; set; }

    public string FixIdent { get; set; }

    public string FixRegion { get; set; }

    public string FixAirportIdent { get; set; }

    public double? FixLonx { get; set; }

    public double? FixLaty { get; set; }

    public string RecommendedFixType { get; set; }

    public string RecommendedFixIdent { get; set; }

    public string RecommendedFixRegion { get; set; }

    public double? RecommendedFixLonx { get; set; }

    public double? RecommendedFixLaty { get; set; }

    public int IsFlyover { get; set; }

    public int IsTrueCourse { get; set; }

    public double? Course { get; set; }

    public double? Distance { get; set; }

    public double? Time { get; set; }

    public double? Theta { get; set; }

    public double? Rho { get; set; }

    public double? Altitude1 { get; set; }

    public double? Altitude2 { get; set; }

    public string SpeedLimitType { get; set; }

    public int? SpeedLimit { get; set; }

    public double? VerticalAngle { get; set; }
}