// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Continentcode
{
    public string Code { get; set; }

    public string Name { get; set; }

    public int GeonameId { get; set; }
}