// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Countryinfo
{
    public string IsoAlpha2 { get; set; }

    public string IsoAlpha3 { get; set; }

    public int? IsoNumeric { get; set; }

    public string FipsCode { get; set; }

    public string Name { get; set; }

    public string Capital { get; set; }

    public double? Areainsqkm { get; set; }

    public int? Population { get; set; }

    public string Continent { get; set; }

    public string Tld { get; set; }

    public string Currency { get; set; }

    public string CurrencyName { get; set; }

    public string Phone { get; set; }

    public string PostalCodeFormat { get; set; }

    public string PostalCodeRegex { get; set; }

    public int GeonameId { get; set; }

    public string Languages { get; set; }

    public string Neighbours { get; set; }

    public string EquivalentFipsCode { get; set; }

    public virtual ICollection<AirportsLocation> AirportsLocations { get; set; } = new List<AirportsLocation>();

    public virtual GeonameEntity Geoname { get; set; }
}