// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class FlightPlan
{
    public string FlightPlanId { get; set; }

    public DateTime DateCreated { get; set; }

    public string AircraftModelId { get; set; }

    public int? StartAirportId { get; set; }

    public int? EndAirportId { get; set; }

    public int? CruiseAltitude { get; set; }

    public decimal? DistanceNm { get; set; }

    public TimeSpan? EstFlightTime { get; set; }

    public DateTime? DateFlown { get; set; }

    public byte? AircraftCrashed { get; set; }

    public string Comments { get; set; }

    public DateTime? LastModified { get; set; }

    public virtual AircraftModel AircraftModel { get; set; }

    public virtual Airport EndAirport { get; set; }

    public virtual ICollection<FlightPlanRoute> FlightPlanRoutes { get; set; } = new List<FlightPlanRoute>();

    public virtual Airport StartAirport { get; set; }
}