// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class FlightPlanRoute
{
    public string FpStepId { get; set; }

    public string FlightPlanId { get; set; }

    public int SequenceNumber { get; set; }

    public int WaypointId { get; set; }

    public int? AirwayId { get; set; }

    public virtual Airway Airway { get; set; }

    public virtual FlightPlan FlightPlan { get; set; }

    public virtual Waypoint Waypoint { get; set; }
}