// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class GeonameEntity
{
    public int GeonameId { get; set; }

    public string Name { get; set; }

    public string Asciiname { get; set; }

    public string Alternatenames { get; set; }

    public double? Latitude { get; set; }

    public double? Longitude { get; set; }

    public string Fclass { get; set; }

    public string Fcode { get; set; }

    public string Country { get; set; }

    public string Cc2 { get; set; }

    public string Admin1 { get; set; }

    public string Admin2 { get; set; }

    public string Admin3 { get; set; }

    public string Admin4 { get; set; }

    public string Admin5 { get; set; }

    public long? Population { get; set; }

    public double? Elevation { get; set; }

    public int? Gtopo30 { get; set; }

    public string Timezone { get; set; }

    public DateOnly? Moddate { get; set; }

    public virtual Countryinfo Countryinfo { get; set; }
}