// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class IlsRunway
{
    public int IlsId { get; set; }

    public string Ident { get; set; }

    public string IlsName { get; set; }

    public string Region { get; set; }

    public string IlsType { get; set; }

    public string PerfIndicator { get; set; }

    public string Provider { get; set; }

    public int? Frequency { get; set; }

    public int? Range { get; set; }

    public double MagVar { get; set; }

    public int HasBackcourse { get; set; }

    public int? DmeRange { get; set; }

    public int? DmeAltitude { get; set; }

    public double? DmeLonx { get; set; }

    public double? DmeLaty { get; set; }

    public int? GsRange { get; set; }

    public double? GsPitch { get; set; }

    public int? GsAltitude { get; set; }

    public double? GsLonx { get; set; }

    public double? GsLaty { get; set; }

    public int? LocRunwayEndId { get; set; }

    public string LocAirportIdent { get; set; }

    public string LocRunwayName { get; set; }

    public double? LocHeading { get; set; }

    public double? LocWidth { get; set; }

    public double? End1Lonx { get; set; }

    public double? End1Laty { get; set; }

    public double? EndMidLonx { get; set; }

    public double? EndMidLaty { get; set; }

    public double? End2Lonx { get; set; }

    public double? End2Laty { get; set; }

    public int Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual RunwaysEnd LocRunwayEnd { get; set; }
}