// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Marker
{
    public int MarkerId { get; set; }

    public int FileId { get; set; }

    public string Ident { get; set; }

    public string Region { get; set; }

    public string Type { get; set; }

    public double Heading { get; set; }

    public int Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }
}