// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class NavSearch
{
    public int NavSearchId { get; set; }

    public int? WaypointId { get; set; }

    public int? WaypointNavId { get; set; }

    public int? VorId { get; set; }

    public int? NdbId { get; set; }

    public int FileId { get; set; }

    public int? AirportId { get; set; }

    public string AirportIdent { get; set; }

    public string Ident { get; set; }

    public string Name { get; set; }

    public string Region { get; set; }

    public int? Range { get; set; }

    public string Type { get; set; }

    public string NavType { get; set; }

    public string ArincType { get; set; }

    public int? Frequency { get; set; }

    public string Channel { get; set; }

    public int? WaypointNumVictorAirway { get; set; }

    public int? WaypointNumJetAirway { get; set; }

    public string SceneryLocalPath { get; set; }

    public string BglFilename { get; set; }

    public double MagVar { get; set; }

    public int? Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }
}