// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class RunwaysStart
{
    public int StartId { get; set; }

    public int AirportId { get; set; }

    public int? RunwayEndId { get; set; }

    public string RunwayName { get; set; }

    public string Type { get; set; }

    public double Heading { get; set; }

    public int? Number { get; set; }

    public int Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual Airport Airport { get; set; }
}