// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class RunwaysEnd
{
    public int RunwayEndId { get; set; }

    public string Name { get; set; }

    public string EndType { get; set; }

    public double OffsetThreshold { get; set; }

    public double BlastPad { get; set; }

    public double Overrun { get; set; }

    public string LeftVasiType { get; set; }

    public double? LeftVasiPitch { get; set; }

    public string RightVasiType { get; set; }

    public double? RightVasiPitch { get; set; }

    public int HasClosedMarkings { get; set; }

    public int HasStolMarkings { get; set; }

    public int IsTakeoff { get; set; }

    public int IsLanding { get; set; }

    public string IsPattern { get; set; }

    public string AppLightSystemType { get; set; }

    public int HasEndLights { get; set; }

    public int HasReils { get; set; }

    public int HasTouchdownLights { get; set; }

    public int? NumStrobes { get; set; }

    public string IlsIdent { get; set; }

    public double Heading { get; set; }

    public int? Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual ICollection<Approach> Approaches { get; set; } = new List<Approach>();

    public virtual ICollection<IlsRunway> IlsRunways { get; set; } = new List<IlsRunway>();

    //public virtual ICollection<Runway> Runways { get; set; } = new List<Runway>();
}