// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Runway
{
    public int RunwayId { get; set; }

    public int AirportId { get; set; }

    public int PrimaryEndId { get; set; }

    public int SecondaryEndId { get; set; }

    public string Surface { get; set; }

    public double? Smoothness { get; set; }

    public string Shoulder { get; set; }

    public double Length { get; set; }

    public double Width { get; set; }

    public double Heading { get; set; }

    public int PatternAltitude { get; set; }

    public int MarkingFlags { get; set; }

    public string EdgeLight { get; set; }

    public string CenterLight { get; set; }

    public int HasCenterRed { get; set; }

    public double PrimaryLonx { get; set; }

    public double PrimaryLaty { get; set; }

    public double SecondaryLonx { get; set; }

    public double SecondaryLaty { get; set; }

    public int Altitude { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual Airport Airport { get; set; }

    public virtual RunwaysEnd PrimaryEnd { get; set; }
}