// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class SimAircraft
{
    public int SimPlaneId { get; set; }

    public string AircraftId { get; set; }

    public virtual AircraftModel Aircraft { get; set; }
}