// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Transition
{
    public int TransitionId { get; set; }

    public int ApproachId { get; set; }

    public string TransitionType { get; set; }

    public string FixType { get; set; }

    public string FixIdent { get; set; }

    public string FixRegion { get; set; }

    public string FixAirportIdent { get; set; }

    public string AircraftCategory { get; set; }

    public int? Altitude { get; set; }

    public string DmeIdent { get; set; }

    public string DmeRegion { get; set; }

    public string DmeAirportIdent { get; set; }

    public double? DmeRadial { get; set; }

    public int? DmeDistance { get; set; }

    public virtual ICollection<TransitionsLeg> TransitionsLegs { get; set; } = new List<TransitionsLeg>();
}