// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AeroSim2026.EFModels;

public partial class Waypoint
{
    public int WaypointId { get; set; }

    public int FileId { get; set; }

    public int? NavId { get; set; }

    public string Ident { get; set; }

    public string WaypointName { get; set; }

    public string Region { get; set; }

    public int? AirportId { get; set; }

    public string AirportIdent { get; set; }

    public int? Artificial { get; set; }

    public string WaypointType { get; set; }

    public string ArincType { get; set; }

    public int NumVictorAirway { get; set; }

    public int NumJetAirway { get; set; }

    public double MagVar { get; set; }

    public double Lonx { get; set; }

    public double Laty { get; set; }

    public virtual ICollection<Airway> AirwayFromWaypoints { get; set; } = new List<Airway>();

    public virtual ICollection<Airway> AirwayToWaypoints { get; set; } = new List<Airway>();

    public virtual ICollection<FlightPlanRoute> FlightPlanRoutes { get; set; } = new List<FlightPlanRoute>();
}